//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public int idTeacher { get; set; }
        public int idPupil { get; set; }
        public int day { get; set; }
        public System.TimeSpan timeBegin { get; set; }
        public System.TimeSpan timeEnd { get; set; }
        public bool active { get; set; }
        public string comment { get; set; }
        public System.DateTime dateBegin { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
    }
}
