//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDetail
    {
        public int idJournal { get; set; }
        public int numTask { get; set; }
        public int resultTask { get; set; }
        public string comment { get; set; }
    }
}
