//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBWorker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbaseEntities : DbContext
    {
        public mydbaseEntities()
            : base("name=mydbaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Journal> Journal { get; set; }
        public DbSet<JournalDetail> JournalDetail { get; set; }
        public DbSet<Pupils> Pupils { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Calendar> Calendar { get; set; }
        public DbSet<Plans> Plans { get; set; }
        public DbSet<Tasks> Tasks { get; set; }
    }
}
