//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pupils
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string grade { get; set; }
        public string target { get; set; }
        public string address { get; set; }
        public string parentName { get; set; }
        public string parentPhone { get; set; }
        public string comment { get; set; }
        public bool active { get; set; }
    }
}
